### ISSUE TITLE
PostgreSQL DECIMAL-typed values becoming R character-typed values via fetch()

### ISSUE THREAD

**Issue by GitChub** [thk686/rpg#3]
First off, thank you Timothy for your great work on the rpg package!

I've noticed that rpg's fetch() seems to turn PostgreSQL DECIMAL-typed values into R character-typed values.  In my situation, that means that all DECIMAL-typed values have to be CAST into a type such as REAL or DOUBLE PRECISION to be fetched (via fetch() ) as numeric values instead of character values.

So, I'm wondering:  Is there a reason for this behavior?  Or is it unintended?

Here's a code snippet that reproduces this behavior:
`str(fetch('SELECT CAST(42.3 AS DECIMAL) AS foo'))`
'data.frame':   1 obs. of  1 variable:
 $ foo: chr "42.3"

And this is an example of casting to work around this behavior:
`str(fetch('SELECT CAST(CAST(42.3 AS DECIMAL) AS REAL) AS foo'))`
'data.frame':   1 obs. of  1 variable:
 $ foo: num 42.3

Thanks in advance.

**Comment by thk686** [comment]
I just have not implemented any conversions beyond basic types. Since I never use decimal types, I've not done that. I am developing a feature that will allow you to register callbacks for conversion of types. Of course everything comes across the wire as text, so really there is very little difference between converting the type yourself and registering a callback.

Look at `register_return_formatter`. It takes the OID of the postgresql type and a callback function to convert to an R-type. There is not an easy way to lookup the OID from a type-name in the database, so for now, you'll just have to know the OID. There is a header in the postgresql source that lists all the OID's.

**Comment by artemklevtsov** [comment]
Working example:
```r
rpg::connect(dbname = "micro")

get_type_oid <- function(typename) {
    res <- rpg::fetch("select typname, oid from pg_type where typname = $1", typename)
    return(as.integer(res[[2]][1]))
}

str(rpg::fetch("SELECT 42.3::decimal AS foo"))
#> SELECT 42.3::decimal AS foo
#> 'data.frame':    1 obs. of  1 variable:
#>  $ foo: chr "42.3"
rpg::register_return_formatter(get_type_oid("numeric"), readr::parse_double)
#> select typname, oid from pg_type where typname = $1
str(rpg::fetch("SELECT 42.3::decimal AS foo"))
#> SELECT 42.3::decimal AS foo
#> 'data.frame':    1 obs. of  1 variable:
#>  $ foo: num 42.3

str(rpg::fetch("SELECT '2018-01-01'::timestamp AS foo"))
#> SELECT '2018-01-01'::timestamp AS foo
#> 'data.frame':    1 obs. of  1 variable:
#>  $ foo: chr "2018-01-01 00:00:00"
rpg::register_return_formatter(get_type_oid("timestamp"), lubridate::ymd_hms)
#> select typname, oid from pg_type where typname = $1
str(rpg::fetch("SELECT '2018-01-01'::timestamp AS foo"))
#> SELECT '2018-01-01'::timestamp AS foo
#> 'data.frame':    1 obs. of  1 variable:
#>  $ foo: POSIXct, format: "2018-01-01"

str(rpg::fetch("SELECT '2018-01-01'::timestamptz AS foo"))
#> SELECT '2018-01-01'::timestamptz AS foo
#> 'data.frame':    1 obs. of  1 variable:
#>  $ foo: chr "2018-01-01 00:00:00+03"
rpg::register_return_formatter(get_type_oid("timestamptz"), lubridate::ymd_hms)
#> select typname, oid from pg_type where typname = $1
str(rpg::fetch("SELECT '2018-01-01'::timestamptz AS foo"))
#> SELECT '2018-01-01'::timestamptz AS foo
#> 'data.frame':    1 obs. of  1 variable:
#>  $ foo: POSIXct, format: "2017-12-31 21:00:00"
```
